
<Structures>
  <Structure Name="Player" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4" Vartype="Float" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="16" Vartype="4 Bytes" Bytesize="4" RLECount="5" DisplayMethod="Unsigned Integer"/>
      <Element Offset="36" Vartype="Float" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="48" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="52" Vartype="Double" Bytesize="8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="60" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="64" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="76" Vartype="Double" Bytesize="8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="84" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="96" Vartype="Double" Bytesize="8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="104" Vartype="Float" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="116" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="120" Vartype="Double" Bytesize="8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="128" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="132" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="144" Vartype="Double" Bytesize="8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="152" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="156" Vartype="Float" Bytesize="4" RLECount="49" DisplayMethod="Unsigned Integer"/>
      <Element Offset="352" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="360" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="364" Vartype="4 Bytes" Bytesize="4" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="380" Vartype="Float" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="392" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="396" Vartype="Float" Bytesize="4" RLECount="12" DisplayMethod="Unsigned Integer"/>
      <Element Offset="444" Vartype="Pointer" Bytesize="4" RLECount="7" DisplayMethod="Unsigned Integer"/>
      <Element Offset="472" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="476" Vartype="Pointer" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="484" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="492" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="496" Vartype="4 Bytes" Bytesize="4" RLECount="5" DisplayMethod="Unsigned Integer"/>
      <Element Offset="516" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="520" Vartype="4 Bytes" Bytesize="4" RLECount="5" DisplayMethod="Unsigned Integer"/>
      <Element Offset="540" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="544" Vartype="4 Bytes" Bytesize="4" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="560" Vartype="Pointer" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="568" Vartype="4 Bytes" Bytesize="4" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="584" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="588" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="596" Vartype="Float" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="608" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="616" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="620" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="624" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="628" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="632" Vartype="4 Bytes" Bytesize="4" RLECount="5" DisplayMethod="Unsigned Integer"/>
      <Element Offset="652" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="656" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="668" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="672" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="680" Vartype="Pointer" Bytesize="4" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="696" Vartype="Float" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="704" Vartype="4 Bytes" Bytesize="4" RLECount="12" DisplayMethod="Unsigned Integer"/>
      <Element Offset="752" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="756" Vartype="4 Bytes" Bytesize="4" RLECount="6" DisplayMethod="Unsigned Integer"/>
      <Element Offset="780" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="784" Vartype="4 Bytes" Bytesize="4" RLECount="6" DisplayMethod="Unsigned Integer"/>
      <Element Offset="808" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="812" Vartype="4 Bytes" Bytesize="4" RLECount="7" DisplayMethod="Unsigned Integer"/>
      <Element Offset="840" Vartype="Float" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="848" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="852" Vartype="Pointer" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="860" Vartype="4 Bytes" Bytesize="4" RLECount="10" DisplayMethod="Unsigned Integer"/>
      <Element Offset="900" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="904" Vartype="4 Bytes" Bytesize="4" RLECount="5" DisplayMethod="Unsigned Integer"/>
      <Element Offset="924" Vartype="Float" Bytesize="4" Description="x (eje x del mapa)" DisplayMethod="Unsigned Integer" BackgroundColor="FFFF80"/>
      <Element Offset="928" Vartype="Float" Bytesize="4" Description="y (eje y del mapa)" DisplayMethod="Unsigned Integer" BackgroundColor="FFFF80"/>
      <Element Offset="932" Vartype="Float" Bytesize="4" Description="z (altura)" DisplayMethod="Unsigned Integer" BackgroundColor="FFFF80"/>
      <Element Offset="936" Vartype="Float" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="948" Vartype="4 Bytes" Bytesize="4" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="964" Vartype="Double" Bytesize="8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="972" Vartype="Float" Bytesize="4" Description="Speed modifier" DisplayMethod="Unsigned Integer" BackgroundColor="FFFF80"/>
      <Element Offset="976" Vartype="Float" Bytesize="4" Description="Attack speed modifier" DisplayMethod="Unsigned Integer" BackgroundColor="FFFF80"/>
      <Element Offset="980" Vartype="Float" Bytesize="4" RLECount="3" Description="Direction" DisplayMethod="Unsigned Integer" BackgroundColor="FFFF80"/>
      <Element Offset="992" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1004" Vartype="Float" Bytesize="4" Description="Direction" DisplayMethod="Unsigned Integer" BackgroundColor="FFFF80"/>
      <Element Offset="1008" Vartype="4 Bytes" Bytesize="4" RLECount="6" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1032" Vartype="Double" Bytesize="8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1040" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1044" Vartype="4 Bytes" Bytesize="4" RLECount="5" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1064" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1068" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1072" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1076" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Hexadecimal"/>
      <Element Offset="1084" Vartype="Float" Bytesize="4" RLECount="7" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1112" Vartype="String" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1116" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1120" Vartype="4 Bytes" Bytesize="4" RLECount="6" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1144" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1148" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1160" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal"/>
      <Element Offset="1164" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1168" Vartype="Float" Bytesize="4" RLECount="5" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1188" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1192" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1196" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1200" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1212" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1216" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1224" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1228" Vartype="4 Bytes" Bytesize="4" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1244" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Hexadecimal"/>
      <Element Offset="1252" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1260" Vartype="Pointer" Bytesize="4" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1276" Vartype="Float" Bytesize="4" RLECount="9" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1312" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Hexadecimal"/>
      <Element Offset="1324" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1332" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1336" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal"/>
      <Element Offset="1340" Vartype="Pointer" Bytesize="4" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1356" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1360" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1364" Vartype="Double" Bytesize="8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1372" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Hexadecimal"/>
      <Element Offset="1380" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1388" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal"/>
      <Element Offset="1392" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1396" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1400" Vartype="Pointer" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="1412" Vartype="4 Bytes" Bytesize="4" RLECount="495" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3392" Vartype="Pointer" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3400" Vartype="4 Bytes" Bytesize="4" RLECount="27" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3508" Vartype="Float" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3516" Vartype="4 Bytes" Bytesize="4" RLECount="4" DisplayMethod="Hexadecimal"/>
      <Element Offset="3532" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3540" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3544" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3548" Vartype="Float" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3560" Vartype="Pointer" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3568" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3572" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3576" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3580" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal"/>
      <Element Offset="3584" Vartype="4 Bytes" Bytesize="4" RLECount="26" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3688" Vartype="String" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3692" Vartype="4 Bytes" Bytesize="4" RLECount="3" DisplayMethod="Hexadecimal"/>
      <Element Offset="3704" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3708" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3712" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal"/>
      <Element Offset="3716" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3724" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3728" Vartype="4 Bytes" Bytesize="4" RLECount="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3744" Vartype="String" Bytesize="5" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3749" Vartype="Byte" Bytesize="1" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3752" Vartype="4 Bytes" Bytesize="4" RLECount="29" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3868" Vartype="Float" Bytesize="4" RLECount="3" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3880" Vartype="4 Bytes" Bytesize="4" RLECount="17" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3948" Vartype="Pointer" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3956" Vartype="4 Bytes" Bytesize="4" RLECount="8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3988" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="3992" Vartype="4 Bytes" Bytesize="4" RLECount="15" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4052" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4056" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4060" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4064" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4068" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4072" Vartype="4 Bytes" Bytesize="4" RLECount="2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4080" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4084" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4088" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4092" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer"/>
    </Elements>
  </Structure>
</Structures>